output "application_hostname" {
  value       = "https://${try(azurerm_app_service.this.0.default_site_hostname, azurerm_function_app.this.0.default_hostname)}"
  description = "The web application URL."
}

output "application_caf_name" {
  value       = azurecaf_name.app_service.result
  description = "The application name generated by the Azure Cloud Adoption Framework."
}

output "database_jdbc_string" {
  value       = try(format(local.database_jdbc_template, split("/", local.config.database.server_id)[8], local.config.database.name), null)
  description = "Database URL."
}
