Microsoft.Cache:
  - AZURE_REDIS_HOST
  - AZURE_REDIS_PORT
  - AZURE_REDIS_DATABASE
  - AZURE_REDIS_SSL
  - AZURE_REDIS_PRINCIPALID
  - AZURE_REDIS_SCOPE
Microsoft.KeyVault:
  - AZURE_KEYVAULT_RESOURCEENDPOINT
  - AZURE_KEYVAULT_CLIENTID
  - AZURE_KEYVAULT_SCOPE
Microsoft.Storage:
  - AZURE_STORAGEBLOB_RESOURCEENDPOINT
  - AZURE_STORAGEBLOB_CLIENTID
  - AZURE_STORAGEBLOB_SCOPE
