output "virtual_machine_caf_name" {
  value       = try(azurecaf_name.linux_virtual_machine_scale_set.0.result, null)
  description = "The virtual machine name generated by Azure Cloud Adoption Framework."
}
